# Generated by Django 6.0.5 on 2026-06-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=1000)),
                ('Price', models.IntegerField()),
                ('Location', models.CharField(max_length=20)),
            ],
        ),
    ]
